import Head from "next/head";

import { api } from "@/utils/api";
import { Button } from "@/components/ui/button";
import { Calendar } from "@/components/ui/calendar";
import { ModeToggle } from "@/components/theme-toggle";

export default function Home() {
  const hello = api.post.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <p className="text-2xl text-white">
            {hello.data ? hello.data.greeting : "Loading tRPC query..."}
          </p>
          <Button>Tester</Button>
          <Calendar mode="single" className="rounded-md border" />
          <ModeToggle />
        </div>
      </main>
    </>
  );
}
