import Head from "next/head";

import { api } from "@/utils/api";
import { Button } from "@/components/ui/button";
import { ModeToggle } from "@/components/theme-toggle";
import Leaderboard from "./Leaderboard";

export default function Home() {
  const players = api.player.findAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-background">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          {players.data !== undefined && <Leaderboard data={players.data} />}
          <Button>Tester</Button>
          <ModeToggle />
        </div>
      </main>
    </>
  );
}
