import Head from "next/head";

import { api } from "@/utils/api";
import { ModeToggle } from "@/components/theme-toggle";
import Leaderboard from "./Leaderboard";
import NavigationBar from "./NavigationBar";

export default function Home() {
  const players = api.player.findAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-background">
        <div className=" fixed right-0 top-0">
          <ModeToggle />
        </div>
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          {players.data !== undefined && <Leaderboard data={players.data} />}
        </div>
        <NavigationBar />
      </main>
    </>
  );
}
