import Head from "next/head";
import NavigationBar from "../components/navigation-bar";
import { Toaster } from "@/components/ui/toaster";
import SettingsBar from "@/components/settings-bar";
import { signIn, useSession } from "next-auth/react";
import Homepage from "@/components/home-page";
import { useRouter } from "next/router";

export default function Layout({ children }: { children: React.ReactNode }) {
  const { data: sessionData, status } = useSession();
  const router = useRouter();

  if (status === "loading") return null;

  if (router.pathname === "/team/join/[id]" && !sessionData)
    return void signIn();

  if (!sessionData?.user && router.pathname === "/") {
    return <Homepage />;
  }

  return (
    <>
      <Head>
        <title>Eloplay</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/table_tennis.png" />
      </Head>
      <main className="relative m-auto flex min-h-screen max-w-[700px] flex-col items-center bg-background">
        <SettingsBar />
        <Toaster />
        {children}
        <NavigationBar />
      </main>
    </>
  );
}
